/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu.driven.program.of.data.structures;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author Christian Jhames
 */
public class pageQueue extends javax.swing.JFrame {
    
    int front = 0;
    int rear = 4;
    int maxsize = 5;
    DataStore dataStore = DataStore.getInstance();
    int[] data = dataStore.getData();

    
    public pageQueue() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        changeQueue = new javax.swing.JButton();
        menuQueue = new javax.swing.JButton();
        exitQueue = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        operationsOnQueue = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Dequeue = new javax.swing.JButton();
        isFull = new javax.swing.JButton();
        count = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        Enqueue = new javax.swing.JButton();
        isEmpty = new javax.swing.JButton();
        peek = new javax.swing.JButton();
        display = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabGeneral = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        labelqueue = new javax.swing.JLabel();
        labelqueue1 = new javax.swing.JLabel();
        labelqueue2 = new javax.swing.JLabel();
        tabDisplay = new javax.swing.JPanel();
        labelOutputDisplay = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaQueueDisplay = new javax.swing.JTextArea();
        tabEnqueue = new javax.swing.JPanel();
        enterButtonQueueEnqueue = new javax.swing.JButton();
        labelDataEnqueue = new javax.swing.JLabel();
        spinnerDataEnqueue = new javax.swing.JSpinner();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(135, 206, 250));

        jPanel4.setBackground(new java.awt.Color(135, 206, 250));
        jPanel4.setLayout(new java.awt.GridLayout(3, 1, 5, 15));

        changeQueue.setBackground(new java.awt.Color(10, 25, 49));
        changeQueue.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        changeQueue.setForeground(new java.awt.Color(255, 255, 255));
        changeQueue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/change.png"))); // NOI18N
        changeQueue.setText("Change");
        changeQueue.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        changeQueue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeQueueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changeQueueMouseExited(evt);
            }
        });
        changeQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeQueueActionPerformed(evt);
            }
        });
        jPanel4.add(changeQueue);

        menuQueue.setBackground(new java.awt.Color(10, 25, 49));
        menuQueue.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        menuQueue.setForeground(new java.awt.Color(255, 255, 255));
        menuQueue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu.png"))); // NOI18N
        menuQueue.setText("Menu");
        menuQueue.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        menuQueue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuQueueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuQueueMouseExited(evt);
            }
        });
        menuQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQueueActionPerformed(evt);
            }
        });
        jPanel4.add(menuQueue);

        exitQueue.setBackground(new java.awt.Color(10, 25, 49));
        exitQueue.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        exitQueue.setForeground(new java.awt.Color(255, 255, 255));
        exitQueue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        exitQueue.setText("Exit");
        exitQueue.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        exitQueue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitQueueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitQueueMouseExited(evt);
            }
        });
        exitQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitQueueActionPerformed(evt);
            }
        });
        jPanel4.add(exitQueue);

        jPanel6.setBackground(new java.awt.Color(135, 206, 250));
        jPanel6.setLayout(new java.awt.GridLayout(2, 2, 55, 0));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/5700800.png"))); // NOI18N
        jLabel10.setText(" 2023 Christian Jhames De Los Reyes. All rights reserved.");
        jPanel6.add(jLabel10);

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/size5.png"))); // NOI18N
        jLabel13.setText("Colveta 2, Mambaling, Cebu City, Cebu, 6000, Philippines");
        jPanel6.add(jLabel13);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/size2.png"))); // NOI18N
        jLabel12.setText(" christianjhamesdelosreyes@gmail.com");
        jPanel6.add(jLabel12);

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/size3.png"))); // NOI18N
        jLabel14.setText(" 0915-044-0670");
        jPanel6.add(jLabel14);

        jLabel11.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel11.setText("A queue is a linear data structure that allows elements to be inserted at one end, called the");

        jLabel15.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel15.setText("rear or tail, and removed from the other end, called the front or head. This means that the");

        jLabel16.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel16.setText("first element added to the queue is the first one to be removed, which follows the");

        jLabel17.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel17.setText("First-In-First-Out (FIFO) principle.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 463, 930, 230));

        jPanel3.setBackground(new java.awt.Color(10, 25, 49));

        operationsOnQueue.setBackground(new java.awt.Color(255, 255, 255));
        operationsOnQueue.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        operationsOnQueue.setForeground(new java.awt.Color(255, 255, 255));
        operationsOnQueue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        operationsOnQueue.setText("Operations on Queue");

        jPanel5.setBackground(new java.awt.Color(10, 25, 49));
        jPanel5.setLayout(new java.awt.GridLayout(3, 1, 5, 35));

        Dequeue.setBackground(new java.awt.Color(102, 204, 255));
        Dequeue.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Dequeue.setText("Dequeue");
        Dequeue.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Dequeue.setPreferredSize(new java.awt.Dimension(87, 12));
        Dequeue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DequeueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DequeueMouseExited(evt);
            }
        });
        Dequeue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DequeueActionPerformed(evt);
            }
        });
        jPanel5.add(Dequeue);

        isFull.setBackground(new java.awt.Color(102, 204, 255));
        isFull.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        isFull.setText("Is Full?");
        isFull.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        isFull.setPreferredSize(new java.awt.Dimension(87, 12));
        isFull.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                isFullMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                isFullMouseExited(evt);
            }
        });
        isFull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isFullActionPerformed(evt);
            }
        });
        jPanel5.add(isFull);

        count.setBackground(new java.awt.Color(102, 204, 255));
        count.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        count.setText("Count");
        count.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        count.setPreferredSize(new java.awt.Dimension(87, 12));
        count.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                countMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                countMouseExited(evt);
            }
        });
        count.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countActionPerformed(evt);
            }
        });
        jPanel5.add(count);

        jPanel7.setBackground(new java.awt.Color(10, 25, 49));
        jPanel7.setLayout(new java.awt.GridLayout(3, 1, 5, 35));

        Enqueue.setBackground(new java.awt.Color(102, 204, 255));
        Enqueue.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Enqueue.setText("Enqueue");
        Enqueue.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Enqueue.setPreferredSize(new java.awt.Dimension(87, 12));
        Enqueue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EnqueueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EnqueueMouseExited(evt);
            }
        });
        Enqueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnqueueActionPerformed(evt);
            }
        });
        jPanel7.add(Enqueue);

        isEmpty.setBackground(new java.awt.Color(102, 204, 255));
        isEmpty.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        isEmpty.setText("Is Empty?");
        isEmpty.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        isEmpty.setPreferredSize(new java.awt.Dimension(87, 12));
        isEmpty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                isEmptyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                isEmptyMouseExited(evt);
            }
        });
        isEmpty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isEmptyActionPerformed(evt);
            }
        });
        jPanel7.add(isEmpty);

        peek.setBackground(new java.awt.Color(102, 204, 255));
        peek.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        peek.setText("Peek");
        peek.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        peek.setPreferredSize(new java.awt.Dimension(87, 12));
        peek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                peekMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                peekMouseExited(evt);
            }
        });
        peek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peekActionPerformed(evt);
            }
        });
        jPanel7.add(peek);

        display.setBackground(new java.awt.Color(102, 204, 255));
        display.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        display.setText("Display");
        display.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        display.setPreferredSize(new java.awt.Dimension(87, 12));
        display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                displayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                displayMouseExited(evt);
            }
        });
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ezgif.com-resize (8).gif"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(operationsOnQueue)
                .addGap(60, 60, 60))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(operationsOnQueue)))
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -3, 490, 460));

        jTabbedPane1.setBackground(new java.awt.Color(10, 25, 49));

        tabGeneral.setBackground(new java.awt.Color(10, 25, 49));

        icon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        icon.setForeground(new java.awt.Color(255, 255, 255));
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ezgif.com-gif-maker (13).gif"))); // NOI18N

        icon1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        icon1.setForeground(new java.awt.Color(255, 255, 255));
        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ezgif.com-gif-maker (10).gif"))); // NOI18N

        labelqueue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelqueue.setForeground(new java.awt.Color(255, 255, 255));
        labelqueue.setText("Front");

        labelqueue1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelqueue1.setForeground(new java.awt.Color(255, 255, 255));
        labelqueue1.setText("Rear");

        labelqueue2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelqueue2.setForeground(new java.awt.Color(255, 255, 255));
        labelqueue2.setText("First In    First Out");

        javax.swing.GroupLayout tabGeneralLayout = new javax.swing.GroupLayout(tabGeneral);
        tabGeneral.setLayout(tabGeneralLayout);
        tabGeneralLayout.setHorizontalGroup(
            tabGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabGeneralLayout.createSequentialGroup()
                .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(103, 103, 103))
            .addGroup(tabGeneralLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(labelqueue, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelqueue1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
            .addGroup(tabGeneralLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(labelqueue2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabGeneralLayout.setVerticalGroup(
            tabGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabGeneralLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(labelqueue2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(icon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tabGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelqueue, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelqueue1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon)
                .addGap(33, 33, 33))
        );

        jTabbedPane1.addTab("tab1", tabGeneral);

        tabDisplay.setBackground(new java.awt.Color(10, 25, 49));

        labelOutputDisplay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelOutputDisplay.setForeground(new java.awt.Color(255, 255, 255));
        labelOutputDisplay.setText("Output:");

        textAreaQueueDisplay.setEditable(false);
        textAreaQueueDisplay.setColumns(20);
        textAreaQueueDisplay.setRows(5);
        jScrollPane1.setViewportView(textAreaQueueDisplay);

        javax.swing.GroupLayout tabDisplayLayout = new javax.swing.GroupLayout(tabDisplay);
        tabDisplay.setLayout(tabDisplayLayout);
        tabDisplayLayout.setHorizontalGroup(
            tabDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDisplayLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(tabDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelOutputDisplay)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        tabDisplayLayout.setVerticalGroup(
            tabDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDisplayLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(labelOutputDisplay)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", tabDisplay);

        tabEnqueue.setBackground(new java.awt.Color(10, 25, 49));

        enterButtonQueueEnqueue.setBackground(new java.awt.Color(102, 204, 255));
        enterButtonQueueEnqueue.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        enterButtonQueueEnqueue.setText("Enter");
        enterButtonQueueEnqueue.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        enterButtonQueueEnqueue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enterButtonQueueEnqueueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enterButtonQueueEnqueueMouseExited(evt);
            }
        });
        enterButtonQueueEnqueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonQueueEnqueueActionPerformed(evt);
            }
        });

        labelDataEnqueue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelDataEnqueue.setForeground(new java.awt.Color(255, 255, 255));
        labelDataEnqueue.setText("Enter the data:");

        javax.swing.GroupLayout tabEnqueueLayout = new javax.swing.GroupLayout(tabEnqueue);
        tabEnqueue.setLayout(tabEnqueueLayout);
        tabEnqueueLayout.setHorizontalGroup(
            tabEnqueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabEnqueueLayout.createSequentialGroup()
                .addGroup(tabEnqueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabEnqueueLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(tabEnqueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDataEnqueue, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerDataEnqueue, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabEnqueueLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(enterButtonQueueEnqueue, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        tabEnqueueLayout.setVerticalGroup(
            tabEnqueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabEnqueueLayout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(labelDataEnqueue, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerDataEnqueue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(enterButtonQueueEnqueue, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        jTabbedPane1.addTab("tab2", tabEnqueue);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, -33, 430, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void isFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isFullActionPerformed
        textAreaQueueDisplay.setText("");
        jTabbedPane1.setSelectedIndex(0);
        
    if (rear == maxsize-1) {  
            javax.swing.JOptionPane.showMessageDialog(pageQueue.this,"Queue is Full!");
        } 
        
    else {  
            javax.swing.JOptionPane.showMessageDialog(pageQueue.this,"Queue is not Full!");
        }   
    }//GEN-LAST:event_isFullActionPerformed

    private void countActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countActionPerformed
        textAreaQueueDisplay.setText("");
        jTabbedPane1.setSelectedIndex(0);
        
        int count = rear - front + 1;
        javax.swing.JOptionPane.showMessageDialog(pageQueue.this,"Number of elements in queue = " + count);
            
    }//GEN-LAST:event_countActionPerformed

    
    private void DequeueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DequeueActionPerformed
        textAreaQueueDisplay.setText("");
        jTabbedPane1.setSelectedIndex(0);   

        int item;   
        if (front == -1 || front > rear) {  
            javax.swing.JOptionPane.showMessageDialog(pageQueue.this,"Underflow!");
        } else {  
            item = data[front];  
            if(front == rear) {  
                front = -1;  
                rear = -1;  
            } else {  
                data[front] = 0;
                front = front + 1;  
            }  
            javax.swing.JOptionPane.showMessageDialog(pageQueue.this,"Item Dequeued! Value = " + item);
            
            // Update the data store with the modified array
            dataStore.setData(data);
        }  
   
    }//GEN-LAST:event_DequeueActionPerformed

    private void enterButtonQueueEnqueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonQueueEnqueueActionPerformed
    {  
        int dataEnqueue = (int) spinnerDataEnqueue.getValue();
        
        if(rear == maxsize-1) {  
            javax.swing.JOptionPane.showMessageDialog(pageQueue.this,"Overflow!");
            return;  
        }  
        if(front == -1 && rear == -1) {  
            front = 0;  
            rear = 0;  
        } else {  
            rear = rear + 1;  
        }  
        data[rear] = dataEnqueue;  
        javax.swing.JOptionPane.showMessageDialog(pageQueue.this,"Item Enqueued! Value = " + dataEnqueue);

        // Update the data store with the modified array
        dataStore.setData(data);
    }  
        
    }//GEN-LAST:event_enterButtonQueueEnqueueActionPerformed

    private void menuQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQueueActionPerformed
        close();
        page3_mainMenu pg3 = new page3_mainMenu();
        pg3.setVisible(true);       // TODO add your handling code here  // TODO add your handling code here:
    }//GEN-LAST:event_menuQueueActionPerformed

    private void changeQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeQueueActionPerformed
        close();
        page2 pg2 = new page2();
        pg2.setVisible(true);  
    }//GEN-LAST:event_changeQueueActionPerformed

    private void exitQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitQueueActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitQueueActionPerformed

    private void changeQueueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeQueueMouseEntered
    changeQueue.setForeground(new Color(0, 0, 0));
    changeQueue.setBackground(new Color(10,82,96));
    }//GEN-LAST:event_changeQueueMouseEntered

    private void changeQueueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeQueueMouseExited
    changeQueue.setForeground(new Color(255, 255, 255));
    changeQueue.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_changeQueueMouseExited

    private void menuQueueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQueueMouseEntered
    menuQueue.setForeground(new Color(0, 0, 0));
    menuQueue.setBackground(new Color(10,82,96));
    }//GEN-LAST:event_menuQueueMouseEntered

    private void menuQueueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQueueMouseExited
    menuQueue.setForeground(new Color(255, 255, 255));
    menuQueue.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_menuQueueMouseExited

    private void exitQueueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitQueueMouseEntered
    exitQueue.setForeground(new Color(0, 0, 0));
    exitQueue.setBackground(new Color(10,82,96));
    }//GEN-LAST:event_exitQueueMouseEntered

    private void exitQueueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitQueueMouseExited
    exitQueue.setForeground(new Color(255, 255, 255));
    exitQueue.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_exitQueueMouseExited

    private void DequeueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DequeueMouseEntered
    Dequeue.setForeground(new Color(255, 255, 255));
    Dequeue.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_DequeueMouseEntered

    private void DequeueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DequeueMouseExited
    Dequeue.setForeground(new Color(0, 0, 0));
    Dequeue.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_DequeueMouseExited

    private void isFullMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isFullMouseEntered
    isFull.setForeground(new Color(255, 255, 255));
    isFull.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_isFullMouseEntered

    private void isFullMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isFullMouseExited
    isFull.setForeground(new Color(0, 0, 0));
    isFull.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_isFullMouseExited

    private void countMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_countMouseEntered
    count.setForeground(new Color(255, 255, 255));
    count.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_countMouseEntered

    private void countMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_countMouseExited
    count.setForeground(new Color(0, 0, 0));
    count.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_countMouseExited

    private void enterButtonQueueEnqueueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterButtonQueueEnqueueMouseEntered
    enterButtonQueueEnqueue.setForeground(new Color(255, 255, 255));
    enterButtonQueueEnqueue.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_enterButtonQueueEnqueueMouseEntered

    private void enterButtonQueueEnqueueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterButtonQueueEnqueueMouseExited
    enterButtonQueueEnqueue.setForeground(new Color(0, 0, 0));
    enterButtonQueueEnqueue.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_enterButtonQueueEnqueueMouseExited

    private void EnqueueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnqueueMouseEntered
    Enqueue.setForeground(new Color(255, 255, 255));
    Enqueue.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_EnqueueMouseEntered

    private void EnqueueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnqueueMouseExited
    Enqueue.setForeground(new Color(0, 0, 0));
    Enqueue.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_EnqueueMouseExited

    private void EnqueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnqueueActionPerformed
    textAreaQueueDisplay.setText("");
    jTabbedPane1.setSelectedIndex(2);
    
    javax.swing.JOptionPane.showMessageDialog(pageQueue.this,"Please provide the data to be Enqueued.");
    }//GEN-LAST:event_EnqueueActionPerformed

    private void isEmptyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isEmptyMouseEntered
    isEmpty.setForeground(new Color(255, 255, 255));
    isEmpty.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_isEmptyMouseEntered

    private void isEmptyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isEmptyMouseExited
    isEmpty.setForeground(new Color(0, 0, 0));
    isEmpty.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_isEmptyMouseExited

    private void isEmptyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isEmptyActionPerformed
     textAreaQueueDisplay.setText("");
    jTabbedPane1.setSelectedIndex(0);
       
    if (front == -1 || front > rear) {  
            javax.swing.JOptionPane.showMessageDialog(pageQueue.this,"Queue is Empty!");
        } 
        
    else {  
            javax.swing.JOptionPane.showMessageDialog(pageQueue.this,"Queue is not Empty!");
        } 
    }//GEN-LAST:event_isEmptyActionPerformed

    private void peekMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peekMouseEntered
    peek.setForeground(new Color(255, 255, 255));
    peek.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_peekMouseEntered

    private void peekMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peekMouseExited
    peek.setForeground(new Color(0, 0, 0));
    peek.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_peekMouseExited

    private void peekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peekActionPerformed
    textAreaQueueDisplay.setText("");
    jTabbedPane1.setSelectedIndex(0);
    
        if (front == -1 || front > rear) {  
            javax.swing.JOptionPane.showMessageDialog(pageQueue.this,"Underflow!");
        } 
        
    else {  
            javax.swing.JOptionPane.showMessageDialog(pageQueue.this,"The Front of the Queue is " + data[front] +" !");
        } 
        
    }//GEN-LAST:event_peekActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
                                       
    textAreaQueueDisplay.setText("");
    jTabbedPane1.setSelectedIndex(1);
    
    int i;
    {  
    if(rear == -1) 
    {  
    javax.swing.JOptionPane.showMessageDialog(pageQueue.this,"Queue is Empty!");    
    }
    else    
    {
        
    textAreaQueueDisplay.append("\n\nfront = index "+front+ "\n");
    textAreaQueueDisplay.append("rear  = index "+rear+ "\n\n\n");
        for(i=front; i<=rear; i++)  
        {  
    textAreaQueueDisplay.append(" Queue ["+ (i+1) +"]   =   "+data[i]+"\n");
        }     
    }  
    } 
  
    }//GEN-LAST:event_displayActionPerformed

    private void displayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayMouseEntered
    display.setForeground(new Color(255, 255, 255));
    display.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_displayMouseEntered

    private void displayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayMouseExited
    display.setForeground(new Color(0, 0, 0));
    display.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_displayMouseExited

 
    public void close(){
       WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
       Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pageQueue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pageQueue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pageQueue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pageQueue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pageQueue().setVisible(true);
                
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dequeue;
    private javax.swing.JButton Enqueue;
    private javax.swing.JButton changeQueue;
    private javax.swing.JButton count;
    private javax.swing.JButton display;
    private javax.swing.JButton enterButtonQueueEnqueue;
    private javax.swing.JButton exitQueue;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel icon1;
    private javax.swing.JButton isEmpty;
    private javax.swing.JButton isFull;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelDataEnqueue;
    private javax.swing.JLabel labelOutputDisplay;
    private javax.swing.JLabel labelqueue;
    private javax.swing.JLabel labelqueue1;
    private javax.swing.JLabel labelqueue2;
    private javax.swing.JButton menuQueue;
    private javax.swing.JLabel operationsOnQueue;
    private javax.swing.JButton peek;
    private javax.swing.JSpinner spinnerDataEnqueue;
    private javax.swing.JPanel tabDisplay;
    private javax.swing.JPanel tabEnqueue;
    private javax.swing.JPanel tabGeneral;
    private javax.swing.JTextArea textAreaQueueDisplay;
    // End of variables declaration//GEN-END:variables
}
