/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu.driven.program.of.data.structures;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author Christian Jhames
 */
public class pageStack extends javax.swing.JFrame {
    
    int top = 4;   
    int maxsize = 4;
    DataStore dataStore = DataStore.getInstance();
    int[] data = dataStore.getData();

    
    public pageStack() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        changeStack = new javax.swing.JButton();
        menuStack = new javax.swing.JButton();
        exitStack = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        operationsOnStack = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        pop = new javax.swing.JButton();
        isFull = new javax.swing.JButton();
        count = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        push = new javax.swing.JButton();
        isEmpty = new javax.swing.JButton();
        peek = new javax.swing.JButton();
        display = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabGeneral = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        labelqueue2 = new javax.swing.JLabel();
        tabDisplay = new javax.swing.JPanel();
        labelOutputDisplay = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaStackDisplay = new javax.swing.JTextArea();
        tabPush = new javax.swing.JPanel();
        enterButtonStackPush = new javax.swing.JButton();
        labelDataPush = new javax.swing.JLabel();
        spinnerDataPush = new javax.swing.JSpinner();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(135, 206, 250));

        jPanel4.setBackground(new java.awt.Color(135, 206, 250));
        jPanel4.setLayout(new java.awt.GridLayout(3, 1, 5, 15));

        changeStack.setBackground(new java.awt.Color(10, 25, 49));
        changeStack.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        changeStack.setForeground(new java.awt.Color(255, 255, 255));
        changeStack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/change.png"))); // NOI18N
        changeStack.setText("Change");
        changeStack.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        changeStack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeStackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changeStackMouseExited(evt);
            }
        });
        changeStack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeStackActionPerformed(evt);
            }
        });
        jPanel4.add(changeStack);

        menuStack.setBackground(new java.awt.Color(10, 25, 49));
        menuStack.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        menuStack.setForeground(new java.awt.Color(255, 255, 255));
        menuStack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu.png"))); // NOI18N
        menuStack.setText("Menu");
        menuStack.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        menuStack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuStackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuStackMouseExited(evt);
            }
        });
        menuStack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuStackActionPerformed(evt);
            }
        });
        jPanel4.add(menuStack);

        exitStack.setBackground(new java.awt.Color(10, 25, 49));
        exitStack.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        exitStack.setForeground(new java.awt.Color(255, 255, 255));
        exitStack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        exitStack.setText("Exit");
        exitStack.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        exitStack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitStackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitStackMouseExited(evt);
            }
        });
        exitStack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitStackActionPerformed(evt);
            }
        });
        jPanel4.add(exitStack);

        jPanel6.setBackground(new java.awt.Color(135, 206, 250));
        jPanel6.setLayout(new java.awt.GridLayout(2, 2, 55, 0));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/5700800.png"))); // NOI18N
        jLabel10.setText(" 2023 Christian Jhames De Los Reyes. All rights reserved.");
        jPanel6.add(jLabel10);

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/size5.png"))); // NOI18N
        jLabel13.setText("Colveta 2, Mambaling, Cebu City, Cebu, 6000, Philippines");
        jPanel6.add(jLabel13);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/size2.png"))); // NOI18N
        jLabel12.setText(" christianjhamesdelosreyes@gmail.com");
        jPanel6.add(jLabel12);

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/size3.png"))); // NOI18N
        jLabel14.setText(" 0915-044-0670");
        jPanel6.add(jLabel14);

        jLabel11.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel11.setText("A stack is a linear data structure that allows elements to be inserted and removed only");

        jLabel15.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel15.setText("from one end, called the top of the stack. This means that the last element added to the");

        jLabel16.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel16.setText("stack is the first one to be removed, which follows the Last-In-First-Out (LIFO) principle.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 463, 930, 230));

        jPanel3.setBackground(new java.awt.Color(10, 25, 49));

        operationsOnStack.setBackground(new java.awt.Color(255, 255, 255));
        operationsOnStack.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        operationsOnStack.setForeground(new java.awt.Color(255, 255, 255));
        operationsOnStack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        operationsOnStack.setText("Operations on Stack");

        jPanel5.setBackground(new java.awt.Color(10, 25, 49));
        jPanel5.setLayout(new java.awt.GridLayout(3, 1, 5, 35));

        pop.setBackground(new java.awt.Color(102, 204, 255));
        pop.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        pop.setText("Pop");
        pop.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pop.setPreferredSize(new java.awt.Dimension(87, 12));
        pop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                popMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                popMouseExited(evt);
            }
        });
        pop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popActionPerformed(evt);
            }
        });
        jPanel5.add(pop);

        isFull.setBackground(new java.awt.Color(102, 204, 255));
        isFull.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        isFull.setText("Is Full?");
        isFull.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        isFull.setPreferredSize(new java.awt.Dimension(87, 12));
        isFull.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                isFullMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                isFullMouseExited(evt);
            }
        });
        isFull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isFullActionPerformed(evt);
            }
        });
        jPanel5.add(isFull);

        count.setBackground(new java.awt.Color(102, 204, 255));
        count.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        count.setText("Count");
        count.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        count.setPreferredSize(new java.awt.Dimension(87, 12));
        count.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                countMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                countMouseExited(evt);
            }
        });
        count.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countActionPerformed(evt);
            }
        });
        jPanel5.add(count);

        jPanel7.setBackground(new java.awt.Color(10, 25, 49));
        jPanel7.setLayout(new java.awt.GridLayout(3, 1, 5, 35));

        push.setBackground(new java.awt.Color(102, 204, 255));
        push.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        push.setText("Push");
        push.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        push.setPreferredSize(new java.awt.Dimension(87, 12));
        push.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pushMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pushMouseExited(evt);
            }
        });
        push.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pushActionPerformed(evt);
            }
        });
        jPanel7.add(push);

        isEmpty.setBackground(new java.awt.Color(102, 204, 255));
        isEmpty.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        isEmpty.setText("Is Empty?");
        isEmpty.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        isEmpty.setPreferredSize(new java.awt.Dimension(87, 12));
        isEmpty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                isEmptyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                isEmptyMouseExited(evt);
            }
        });
        isEmpty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isEmptyActionPerformed(evt);
            }
        });
        jPanel7.add(isEmpty);

        peek.setBackground(new java.awt.Color(102, 204, 255));
        peek.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        peek.setText("Peek");
        peek.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        peek.setPreferredSize(new java.awt.Dimension(87, 12));
        peek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                peekMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                peekMouseExited(evt);
            }
        });
        peek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peekActionPerformed(evt);
            }
        });
        jPanel7.add(peek);

        display.setBackground(new java.awt.Color(102, 204, 255));
        display.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        display.setText("Display");
        display.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        display.setPreferredSize(new java.awt.Dimension(87, 12));
        display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                displayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                displayMouseExited(evt);
            }
        });
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ezgif.com-resize (8).gif"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 162, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(operationsOnStack)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(operationsOnStack))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -3, 490, 460));

        jTabbedPane1.setBackground(new java.awt.Color(10, 25, 49));

        tabGeneral.setBackground(new java.awt.Color(10, 25, 49));

        icon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        icon.setForeground(new java.awt.Color(255, 255, 255));
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ezgif.com-resize (2).gif"))); // NOI18N

        labelqueue2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelqueue2.setForeground(new java.awt.Color(255, 255, 255));
        labelqueue2.setText("Last In   First Out");

        javax.swing.GroupLayout tabGeneralLayout = new javax.swing.GroupLayout(tabGeneral);
        tabGeneral.setLayout(tabGeneralLayout);
        tabGeneralLayout.setHorizontalGroup(
            tabGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabGeneralLayout.createSequentialGroup()
                .addGroup(tabGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabGeneralLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(icon))
                    .addGroup(tabGeneralLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(labelqueue2)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        tabGeneralLayout.setVerticalGroup(
            tabGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabGeneralLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(labelqueue2)
                .addGap(18, 18, 18)
                .addComponent(icon)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", tabGeneral);

        tabDisplay.setBackground(new java.awt.Color(10, 25, 49));

        labelOutputDisplay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelOutputDisplay.setForeground(new java.awt.Color(255, 255, 255));
        labelOutputDisplay.setText("Output:");

        textAreaStackDisplay.setEditable(false);
        textAreaStackDisplay.setColumns(20);
        textAreaStackDisplay.setRows(5);
        jScrollPane1.setViewportView(textAreaStackDisplay);

        javax.swing.GroupLayout tabDisplayLayout = new javax.swing.GroupLayout(tabDisplay);
        tabDisplay.setLayout(tabDisplayLayout);
        tabDisplayLayout.setHorizontalGroup(
            tabDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDisplayLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(tabDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelOutputDisplay)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        tabDisplayLayout.setVerticalGroup(
            tabDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDisplayLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(labelOutputDisplay)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", tabDisplay);

        tabPush.setBackground(new java.awt.Color(10, 25, 49));

        enterButtonStackPush.setBackground(new java.awt.Color(102, 204, 255));
        enterButtonStackPush.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        enterButtonStackPush.setText("Enter");
        enterButtonStackPush.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        enterButtonStackPush.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enterButtonStackPushMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enterButtonStackPushMouseExited(evt);
            }
        });
        enterButtonStackPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonStackPushActionPerformed(evt);
            }
        });

        labelDataPush.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelDataPush.setForeground(new java.awt.Color(255, 255, 255));
        labelDataPush.setText("Enter the data:");

        javax.swing.GroupLayout tabPushLayout = new javax.swing.GroupLayout(tabPush);
        tabPush.setLayout(tabPushLayout);
        tabPushLayout.setHorizontalGroup(
            tabPushLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPushLayout.createSequentialGroup()
                .addGroup(tabPushLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabPushLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(tabPushLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDataPush, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerDataPush, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabPushLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(enterButtonStackPush, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        tabPushLayout.setVerticalGroup(
            tabPushLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPushLayout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(labelDataPush, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerDataPush, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(enterButtonStackPush, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        jTabbedPane1.addTab("tab2", tabPush);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, -33, 430, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void isFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isFullActionPerformed
        textAreaStackDisplay.setText("");
        jTabbedPane1.setSelectedIndex(0);
        
    if (top == maxsize) {  
            javax.swing.JOptionPane.showMessageDialog(pageStack.this,"Stack is Full!");
        } 
        
    else {  
            javax.swing.JOptionPane.showMessageDialog(pageStack.this,"Stack is not Full!");
        }   
    }//GEN-LAST:event_isFullActionPerformed

    private void countActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countActionPerformed
        textAreaStackDisplay.setText("");
        jTabbedPane1.setSelectedIndex(0);
        
        switch (top) {
            case -1:
                javax.swing.JOptionPane.showMessageDialog(pageStack.this,"No elements in the Stack!");
                break;
            case 0:
                javax.swing.JOptionPane.showMessageDialog(pageStack.this,"There is "+ (top+1) + " element in the Stack");
                break;
            default:
                javax.swing.JOptionPane.showMessageDialog(pageStack.this,"There are "+ (top+1) + " elements in the Stack");
                break;
        }
            
    }//GEN-LAST:event_countActionPerformed

    
    private void popActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popActionPerformed
        textAreaStackDisplay.setText("");
        jTabbedPane1.setSelectedIndex(0);   

        if (top == -1) {  
            javax.swing.JOptionPane.showMessageDialog(pageStack.this,"Underflow!");
        } 
        
        else {  
            int poppedValue = data[top];
            top--;
            javax.swing.JOptionPane.showMessageDialog(pageStack.this,"Item popped! Value = " + poppedValue);
        }       

            data[top+1] = 0;
            dataStore.setData(data);
     
    }//GEN-LAST:event_popActionPerformed

    private void enterButtonStackPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonStackPushActionPerformed
    
        int dataPush = (int) spinnerDataPush.getValue();
        
        
    if (top == maxsize) {  
        javax.swing.JOptionPane.showMessageDialog(pageStack.this,"Overflow!");
    } else {  
        
        top++;
        data[top] = dataPush;
  
        javax.swing.JOptionPane.showMessageDialog(pageStack.this,"Item pushed! Value = " + dataPush);

        // Update the data store with the modified array
        dataStore.setData(data);
    }  
        
    }//GEN-LAST:event_enterButtonStackPushActionPerformed

    private void menuStackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuStackActionPerformed
        close();
        page3_mainMenu pg3 = new page3_mainMenu();
        pg3.setVisible(true);       // TODO add your handling code here  // TODO add your handling code here:
    }//GEN-LAST:event_menuStackActionPerformed

    private void changeStackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeStackActionPerformed
        close();
        page2 pg2 = new page2();
        pg2.setVisible(true);  
    }//GEN-LAST:event_changeStackActionPerformed

    private void exitStackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitStackActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitStackActionPerformed

    private void changeStackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeStackMouseEntered
    changeStack.setForeground(new Color(0, 0, 0));
    changeStack.setBackground(new Color(10,82,96));
    }//GEN-LAST:event_changeStackMouseEntered

    private void changeStackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeStackMouseExited
    changeStack.setForeground(new Color(255, 255, 255));
    changeStack.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_changeStackMouseExited

    private void menuStackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuStackMouseEntered
    menuStack.setForeground(new Color(0, 0, 0));
    menuStack.setBackground(new Color(10,82,96));
    }//GEN-LAST:event_menuStackMouseEntered

    private void menuStackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuStackMouseExited
    menuStack.setForeground(new Color(255, 255, 255));
    menuStack.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_menuStackMouseExited

    private void exitStackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitStackMouseEntered
    exitStack.setForeground(new Color(0, 0, 0));
    exitStack.setBackground(new Color(10,82,96));
    }//GEN-LAST:event_exitStackMouseEntered

    private void exitStackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitStackMouseExited
    exitStack.setForeground(new Color(255, 255, 255));
    exitStack.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_exitStackMouseExited

    private void popMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popMouseEntered
    pop.setForeground(new Color(255, 255, 255));
    pop.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_popMouseEntered

    private void popMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popMouseExited
    pop.setForeground(new Color(0, 0, 0));
    pop.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_popMouseExited

    private void isFullMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isFullMouseEntered
    isFull.setForeground(new Color(255, 255, 255));
    isFull.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_isFullMouseEntered

    private void isFullMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isFullMouseExited
    isFull.setForeground(new Color(0, 0, 0));
    isFull.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_isFullMouseExited

    private void countMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_countMouseEntered
    count.setForeground(new Color(255, 255, 255));
    count.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_countMouseEntered

    private void countMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_countMouseExited
    count.setForeground(new Color(0, 0, 0));
    count.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_countMouseExited

    private void enterButtonStackPushMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterButtonStackPushMouseEntered
    enterButtonStackPush.setForeground(new Color(255, 255, 255));
    enterButtonStackPush.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_enterButtonStackPushMouseEntered

    private void enterButtonStackPushMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterButtonStackPushMouseExited
    enterButtonStackPush.setForeground(new Color(0, 0, 0));
    enterButtonStackPush.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_enterButtonStackPushMouseExited

    private void pushMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pushMouseEntered
    push.setForeground(new Color(255, 255, 255));
    push.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_pushMouseEntered

    private void pushMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pushMouseExited
    push.setForeground(new Color(0, 0, 0));
    push.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_pushMouseExited

    private void pushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pushActionPerformed
    textAreaStackDisplay.setText("");
    jTabbedPane1.setSelectedIndex(2);
    
    javax.swing.JOptionPane.showMessageDialog(pageStack.this,"Please provide the data to be pushed.");
    }//GEN-LAST:event_pushActionPerformed

    private void isEmptyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isEmptyMouseEntered
    isEmpty.setForeground(new Color(255, 255, 255));
    isEmpty.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_isEmptyMouseEntered

    private void isEmptyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isEmptyMouseExited
    isEmpty.setForeground(new Color(0, 0, 0));
    isEmpty.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_isEmptyMouseExited

    private void isEmptyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isEmptyActionPerformed
    textAreaStackDisplay.setText("");
    jTabbedPane1.setSelectedIndex(0);
       
    if (top == -1) {  
            javax.swing.JOptionPane.showMessageDialog(pageStack.this,"Stack is Empty!");
        } 
        
    else {  
            javax.swing.JOptionPane.showMessageDialog(pageStack.this,"Stack is not Empty!");
        } 
    }//GEN-LAST:event_isEmptyActionPerformed

    private void peekMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peekMouseEntered
    peek.setForeground(new Color(255, 255, 255));
    peek.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_peekMouseEntered

    private void peekMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peekMouseExited
    peek.setForeground(new Color(0, 0, 0));
    peek.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_peekMouseExited

    private void peekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peekActionPerformed
    textAreaStackDisplay.setText("");
    jTabbedPane1.setSelectedIndex(0);
    
        if (top == -1) {  
            javax.swing.JOptionPane.showMessageDialog(pageStack.this,"Underflow!");
        } 
        
    else {  
            javax.swing.JOptionPane.showMessageDialog(pageStack.this,"Top of the Stack is " + data[top] +" !");
        } 
        
    }//GEN-LAST:event_peekActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
    textAreaStackDisplay.setText("");
    jTabbedPane1.setSelectedIndex(1);

    for (int i=top ; i>=0; i--) {  
        String element = " " + data[i] + " "; // add spaces for padding
        String dashes = "-".repeat(element.length() + 2); // create dashes for top and bottom
        String formattedOutput = String.format("\t%s\n\t|%s|\n\t%s\n", dashes, element, dashes);
        if (i > 0) {
            formattedOutput += "\t  ↑\n";
        }
        textAreaStackDisplay.append(formattedOutput);
    }  
    
    if(top == -1) {  
        javax.swing.JOptionPane.showMessageDialog(pageStack.this,"Stack is Empty!");
    }  
    }//GEN-LAST:event_displayActionPerformed

    private void displayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayMouseEntered
    display.setForeground(new Color(255, 255, 255));
    display.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_displayMouseEntered

    private void displayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayMouseExited
    display.setForeground(new Color(0, 0, 0));
    display.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_displayMouseExited

 
    public void close(){
       WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
       Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pageStack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pageStack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pageStack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pageStack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pageStack().setVisible(true);
                
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeStack;
    private javax.swing.JButton count;
    private javax.swing.JButton display;
    private javax.swing.JButton enterButtonStackPush;
    private javax.swing.JButton exitStack;
    private javax.swing.JLabel icon;
    private javax.swing.JButton isEmpty;
    private javax.swing.JButton isFull;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelDataPush;
    private javax.swing.JLabel labelOutputDisplay;
    private javax.swing.JLabel labelqueue2;
    private javax.swing.JButton menuStack;
    private javax.swing.JLabel operationsOnStack;
    private javax.swing.JButton peek;
    private javax.swing.JButton pop;
    private javax.swing.JButton push;
    private javax.swing.JSpinner spinnerDataPush;
    private javax.swing.JPanel tabDisplay;
    private javax.swing.JPanel tabGeneral;
    private javax.swing.JPanel tabPush;
    private javax.swing.JTextArea textAreaStackDisplay;
    // End of variables declaration//GEN-END:variables
}
