/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu.driven.program.of.data.structures;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author Christian Jhames
 */
public class pageSearching extends javax.swing.JFrame {

    /**
     * Creates new form pageArray
     */
    public pageSearching() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        changeArray = new javax.swing.JButton();
        menuArray = new javax.swing.JButton();
        exitArray = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        operationsOnArray = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        binary = new javax.swing.JButton();
        linear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabTraverse = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabSearch = new javax.swing.JPanel();
        enterButtonSearch = new javax.swing.JButton();
        labelDataSearch = new javax.swing.JLabel();
        spinnerDataSearch = new javax.swing.JSpinner();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(135, 206, 250));

        jPanel4.setBackground(new java.awt.Color(135, 206, 250));
        jPanel4.setLayout(new java.awt.GridLayout(3, 1, 5, 15));

        changeArray.setBackground(new java.awt.Color(10, 25, 49));
        changeArray.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        changeArray.setForeground(new java.awt.Color(255, 255, 255));
        changeArray.setIcon(new javax.swing.ImageIcon(getClass().getResource("/change.png"))); // NOI18N
        changeArray.setText("Change");
        changeArray.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        changeArray.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeArrayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changeArrayMouseExited(evt);
            }
        });
        changeArray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeArrayActionPerformed(evt);
            }
        });
        jPanel4.add(changeArray);

        menuArray.setBackground(new java.awt.Color(10, 25, 49));
        menuArray.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        menuArray.setForeground(new java.awt.Color(255, 255, 255));
        menuArray.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu.png"))); // NOI18N
        menuArray.setText("Menu");
        menuArray.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        menuArray.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuArrayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuArrayMouseExited(evt);
            }
        });
        menuArray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArrayActionPerformed(evt);
            }
        });
        jPanel4.add(menuArray);

        exitArray.setBackground(new java.awt.Color(10, 25, 49));
        exitArray.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        exitArray.setForeground(new java.awt.Color(255, 255, 255));
        exitArray.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        exitArray.setText("Exit");
        exitArray.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        exitArray.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitArrayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitArrayMouseExited(evt);
            }
        });
        exitArray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitArrayActionPerformed(evt);
            }
        });
        jPanel4.add(exitArray);

        jPanel6.setBackground(new java.awt.Color(135, 206, 250));
        jPanel6.setLayout(new java.awt.GridLayout(2, 2, 55, 0));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/5700800.png"))); // NOI18N
        jLabel10.setText(" 2023 Christian Jhames De Los Reyes. All rights reserved.");
        jPanel6.add(jLabel10);

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/size5.png"))); // NOI18N
        jLabel13.setText("Colveta 2, Mambaling, Cebu City, Cebu, 6000, Philippines");
        jPanel6.add(jLabel13);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/size2.png"))); // NOI18N
        jLabel12.setText(" christianjhamesdelosreyes@gmail.com");
        jPanel6.add(jLabel12);

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/size3.png"))); // NOI18N
        jLabel14.setText(" 0915-044-0670");
        jPanel6.add(jLabel14);

        jLabel9.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel9.setText("Linear Search: Sequentially checks each element in a collection until the target element");

        jLabel11.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel11.setText("is found or the end is reached.");

        jLabel15.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel15.setText("Binary Search: Efficiently searches a sorted collection by repeatedly dividing");

        jLabel16.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel16.setText("the search space in half.     ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addGap(28, 28, 28)))
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 463, 930, 230));

        jPanel3.setBackground(new java.awt.Color(10, 25, 49));

        operationsOnArray.setBackground(new java.awt.Color(255, 255, 255));
        operationsOnArray.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        operationsOnArray.setForeground(new java.awt.Color(255, 255, 255));
        operationsOnArray.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        operationsOnArray.setText("Types of Searching");

        jPanel5.setBackground(new java.awt.Color(10, 25, 49));
        jPanel5.setLayout(new java.awt.GridLayout(2, 1, 5, 35));

        binary.setBackground(new java.awt.Color(102, 204, 255));
        binary.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        binary.setText("Binary Search");
        binary.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        binary.setPreferredSize(new java.awt.Dimension(87, 12));
        binary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                binaryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                binaryMouseExited(evt);
            }
        });
        binary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binaryActionPerformed(evt);
            }
        });
        jPanel5.add(binary);

        linear.setBackground(new java.awt.Color(102, 204, 255));
        linear.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        linear.setText("Linear Search");
        linear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        linear.setPreferredSize(new java.awt.Dimension(87, 12));
        linear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linearMouseExited(evt);
            }
        });
        linear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linearActionPerformed(evt);
            }
        });
        jPanel5.add(linear);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ezgif.com-resize (8).gif"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)
                        .addComponent(operationsOnArray))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(operationsOnArray)))
                .addGap(85, 85, 85)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -3, 490, 460));

        jTabbedPane1.setBackground(new java.awt.Color(10, 25, 49));

        tabTraverse.setBackground(new java.awt.Color(10, 25, 49));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ezgif.com-resize (22).gif"))); // NOI18N

        tabSearch.setBackground(new java.awt.Color(10, 25, 49));

        enterButtonSearch.setBackground(new java.awt.Color(102, 204, 255));
        enterButtonSearch.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        enterButtonSearch.setText("Enter");
        enterButtonSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        enterButtonSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enterButtonSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enterButtonSearchMouseExited(evt);
            }
        });
        enterButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonSearchActionPerformed(evt);
            }
        });

        labelDataSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelDataSearch.setForeground(new java.awt.Color(255, 255, 255));
        labelDataSearch.setText("Enter the data:");

        javax.swing.GroupLayout tabSearchLayout = new javax.swing.GroupLayout(tabSearch);
        tabSearch.setLayout(tabSearchLayout);
        tabSearchLayout.setHorizontalGroup(
            tabSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSearchLayout.createSequentialGroup()
                .addGroup(tabSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabSearchLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(tabSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDataSearch)
                            .addComponent(spinnerDataSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabSearchLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(enterButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        tabSearchLayout.setVerticalGroup(
            tabSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSearchLayout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addComponent(labelDataSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spinnerDataSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(enterButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout tabTraverseLayout = new javax.swing.GroupLayout(tabTraverse);
        tabTraverse.setLayout(tabTraverseLayout);
        tabTraverseLayout.setHorizontalGroup(
            tabTraverseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTraverseLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(tabTraverseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabTraverseLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tabSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        tabTraverseLayout.setVerticalGroup(
            tabTraverseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTraverseLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
            .addGroup(tabTraverseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabTraverseLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tabSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab1", tabTraverse);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, -33, 430, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void linearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linearActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        javax.swing.JOptionPane.showMessageDialog(pageSearching.this,"Please provide the data to be searched using Linear Search.");
    }//GEN-LAST:event_linearActionPerformed

    private void binaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binaryActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        javax.swing.JOptionPane.showMessageDialog(pageSearching.this,"Please provide the data to be searched using Binary Search.");
    }//GEN-LAST:event_binaryActionPerformed

    private void menuArrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArrayActionPerformed
        close();
        page3_algo pg3 = new page3_algo();
        pg3.setVisible(true);       // TODO add your handling code here  // TODO add your handling code here:
    }//GEN-LAST:event_menuArrayActionPerformed

    private void changeArrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeArrayActionPerformed
        close();
        page2 pg2 = new page2();
        pg2.setVisible(true);
    }//GEN-LAST:event_changeArrayActionPerformed

    private void exitArrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitArrayActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitArrayActionPerformed

    private void changeArrayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeArrayMouseEntered
    changeArray.setForeground(new Color(0, 0, 0));
    changeArray.setBackground(new Color(10,82,96));
    }//GEN-LAST:event_changeArrayMouseEntered

    private void changeArrayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeArrayMouseExited
    changeArray.setForeground(new Color(255, 255, 255));
    changeArray.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_changeArrayMouseExited

    private void menuArrayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuArrayMouseEntered
    menuArray.setForeground(new Color(0, 0, 0));
    menuArray.setBackground(new Color(10,82,96));
    }//GEN-LAST:event_menuArrayMouseEntered

    private void menuArrayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuArrayMouseExited
    menuArray.setForeground(new Color(255, 255, 255));
    menuArray.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_menuArrayMouseExited

    private void exitArrayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitArrayMouseEntered
    exitArray.setForeground(new Color(0, 0, 0));
    exitArray.setBackground(new Color(10,82,96));
    }//GEN-LAST:event_exitArrayMouseEntered

    private void exitArrayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitArrayMouseExited
    exitArray.setForeground(new Color(255, 255, 255));
    exitArray.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_exitArrayMouseExited

    private void binaryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_binaryMouseEntered
    binary.setForeground(new Color(255, 255, 255));
    binary.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_binaryMouseEntered

    private void binaryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_binaryMouseExited
    binary.setForeground(new Color(0, 0, 0));
    binary.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_binaryMouseExited

    private void linearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linearMouseEntered
    linear.setForeground(new Color(255, 255, 255));
    linear.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_linearMouseEntered

    private void linearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linearMouseExited
    linear.setForeground(new Color(0, 0, 0));
    linear.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_linearMouseExited

    private void enterButtonSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterButtonSearchMouseEntered
        enterButtonSearch.setForeground(new Color(255, 255, 255));
        enterButtonSearch.setBackground(new Color(10, 25, 49));
    }//GEN-LAST:event_enterButtonSearchMouseEntered

    private void enterButtonSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterButtonSearchMouseExited
        enterButtonSearch.setForeground(new Color(0, 0, 0));
        enterButtonSearch.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_enterButtonSearchMouseExited

    private void enterButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonSearchActionPerformed
    int value = (int) spinnerDataSearch.getValue();

    DataStore dataStore = DataStore.getInstance();
    int[] data = dataStore.getData();

    boolean elementFound;

    if (binary.isSelected()) {
        // Perform binary search
        elementFound = binarySearch(data, value);
    } else {
        // Perform linear search
        elementFound = linearSearch(data, value);
    }

    if (elementFound) {
        javax.swing.JOptionPane.showMessageDialog(pageSearching.this, "Element found!");
    } else {
        javax.swing.JOptionPane.showMessageDialog(pageSearching.this, "Element not found!");
    }
    }//GEN-LAST:event_enterButtonSearchActionPerformed

    
    private boolean binarySearch(int[] data, int value) {
    int low = 0;
    int high = data.length - 1;

    while (low <= high) {
        int mid = (low + high) / 2;

        if (data[mid] == value) {
            return true; // Element found
        } else if (data[mid] < value) {
            low = mid + 1;
        } else {
            high = mid - 1;
        }
    }

    return false; // Element not found
}

private boolean linearSearch(int[] data, int value) {
    for (int i = 0; i < data.length; i++) {
        if (data[i] == value) {
            return true; // Element found
        }
    }

    return false; // Element not found
}
 
    public void close(){
       WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
       Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pageSearching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pageSearching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pageSearching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pageSearching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pageSearching().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton binary;
    private javax.swing.JButton changeArray;
    private javax.swing.JButton enterButtonSearch;
    private javax.swing.JButton exitArray;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelDataSearch;
    private javax.swing.JButton linear;
    private javax.swing.JButton menuArray;
    private javax.swing.JLabel operationsOnArray;
    private javax.swing.JSpinner spinnerDataSearch;
    private javax.swing.JPanel tabSearch;
    private javax.swing.JPanel tabTraverse;
    // End of variables declaration//GEN-END:variables
}
